install.packages('sqldf')
install.packages('dplyr')
install.packages("igraph")
library(igraph)
g = graph(edges = c(1,2,1,3,1,4,3,4), n = 4, directed = FALSE)
is.directed(g)
summary(g)
V(g)$name = c('Mike', 'Lisa', 'John', 'Frank')
V(g)$gender = c('M', 'F', 'M', 'M')
summary(g)
plot(g)
degree(g)
degree(g,normalized = T)
table(degree(g))
betweenness(graph = g,normalized = F)
betweenness(graph = g,normalized = T)
closeness(g)
evcent(g)$vector
?graph

g = graph(edges = c(1,2,2,3,2,4,3,5,4,5,4,6,5,6,5,7,5,8,6,7), n = 8, directed = FALSE)
is.directed(g)
summary(g)
V(g)$name = c('A', 'B', 'C', 'D','E','G','H','F')
#V(g)$gender = c('M', 'F', 'M', 'M')
summary(g)
plot(g)
degree(g)
degree(g,normalized = T)
table(degree(g))
plot(table(degree(g)))
betweenness(graph = g,normalized = F)
betweenness(graph = g,normalized = T)
closeness(g)
evcent(g)$vector
?graph
